# NOM: NYUMEA PEHA DARYL GERVAIS
# MATRICULE: 24H2571
# NIVEAU : LICENCE 2
# UNIVERSITE : UNIVERSITE DE YAOUNDE 1

# render.yaml pour LMS Cameroun
services:
  - type: web
    name: lms-cameroun
    runtime: php
    
    # Configuration pour le serveur PHP sur Render
    # Si index.php est à la racine du dépôt Git, on n'utilise pas rootDir.
    buildCommand: "composer install --no-dev --no-scripts --no-autoloader"
    
    envVars:
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: CLOUDINARY_CLOUD_NAME
        value: "dfymenyrx"
      - key: CLOUDINARY_API_KEY
        fromSecret: CLOUDINARY_API_KEY

# NOM: NYUMEA PEHA DARYL GERVAIS
# MATRICULE: 24H2571
# NIVEAU : LICENCE 2
# UNIVERSITE : UNIVERSITE DE YAOUNDE 1

      - key: CLOUDINARY_API_SECRET
        fromSecret: CLOUDINARY_API_SECRET
      - key: APP_NAME
        value: "LMS Cameroun"
      - key: APP_ENV
        value: "production"
      - key: APP_BASE_URL
        value: "https://lms-version-1.onrender.com"
      - key: SESSION_TIMEOUT
        value: "3600"
      - key: BREVO_SMTP_HOST
        value: "smtp-relay.brevo.com"
      - key: BREVO_SMTP_PORT
        value: "587"
      - key: BREVO_SMTP_USER
        fromSecret: BREVO_SMTP_USER
      - key: BREVO_SMTP_PASS
        fromSecret: BREVO_SMTP_PASS
      - key: BREVO_API_KEY
        fromSecret: BREVO_API_KEY
      - key: EMAIL_FROM
        value: "gervais.nyumea@facsciences-uy1.cm"
