# NOM: NYUMEA PEHA DARYL GERVAIS
# MATRICULE: 24H2571
# NIVEAU : LICENCE 2
# UNIVERSITE : UNIVERSITE DE YAOUNDE 1

#!/bin/bash

# NOM: NYUMEA PEHA DARYL GERVAIS
# MATRICULE: 24H2571
# NIVEAU : LICENCE 2
# UNIVERSITE : UNIVERSITE DE YAOUNDE 1

cd "$(dirname "$0")"

echo "Arret de LMS Cameroun..."
docker compose down

echo "LMS Cameroun arrete."
